myapp/urls.py
from django.urls import path,include
from .views import todoList,update,search,delete,create

urlpatterns = [
    path('',todoList),
    path('create/',create,name='create'),
    path('update/<int:id>',update,name='update'),
    path('delete/<int:id>',delete,name='delete'),
    path('search',search)
]

todolist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

myapp/models.py
from django.db import models

# Create your models here.

class ToDoList(models.Model):
    textField = models.CharField(max_length =450)

    def __str__(self):
        return self.textField

myapp/forms.py
from django.forms import ModelForm
from .models import ToDoList

class ListForm(ModelForm):
    class Meta:
        model = ToDoList
        fields = ['textField']
        labels = {'textField':'Enter Here'}

myapp/views.py
from django.http.response import JsonResponse
from django.shortcuts import render,redirect
from .forms import ListForm
from .models import ToDoList
import json
from django.core import serializers
# Create your views here.


def todoList(request):
    obj = ToDoList.objects.all()
    form = ListForm
    context = {
        'obj': obj,
        'form' : form

    }
    return render(request,'index.html',context)

def create(request):
    if request.method =='POST':
        form = ListForm(request.POST)
        form.save()
        return redirect('/')
    
    
def update(request,id):
    person = ToDoList.objects.get(id=id)
    if request.method =='POST':
        data = request.POST['textField']
        person.textField = data
        person.save()
        return redirect('/')
    content={
        'person':person
    }  
    return render(request,'update.html',content)


def delete(request,id):
    person = ToDoList.objects.get(id=id or None)
    person.delete()
    return redirect('/')

def search(request):
    query = request.GET['query']
    allPost = ToDoList.objects.filter(textField__icontains=query)
    posting = {'allPost':allPost}

    return render(request,'search.html',posting)

myapp/templates/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDoList</title>
    <style>

        *{
            margin: 0px;
            padding: 0px;
            /* box-sizing: border-box; */
            /* overflow: hidden; */
        }
        h1{
            font-family: 'Courier New', Courier, monospace;
            text-align: center;
            margin: 2rem 0 4rem 0;
        }

        form{
            margin: 1rem;
            text-align: center;
        }

        form label{
            font-family:Verdana, Geneva, Tahoma, sans-serif;
            display: block;
            margin-bottom: 0.5rem;
        }
        form input[type='text']{
            width: 50%;
            height:2.7rem;
            padding: 10px;
            font-size:1rem;
            transition: width 0.4s,height 0.4s
        }

        form input[type='text']:focus{
            width:51%;
            height:2.9rem;
        }

        form input[type='submit']{
            display: block;
            margin:1rem auto;
            width: 5rem;
            height: 2.5rem;
            border: 2px solid black;
            font-weight: bold;
            color: white;
            background-color: steelblue;
            cursor: pointer;
            transition: width 0.4s,height 0.4s;
        }
        form input[type='submit']:hover,.modelForm button:hover{
            width: 5.5rem;
            height:3rem;
        }

        .tableContainer{
            margin: 0 1rem 0 1rem;
        }
       .tableContainer table {
        font-family: helvetica,arial, sans-serif;
        width: 100%;
        }   

        td, th {
            border: 1.5px solid #131212;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
        td button{
            border: none;
            color: white;
            padding: 10px 24px;
            font-size: 14px;
            cursor: pointer;
            
        }


    </style>
</head>
<body>

    <form action="/search" method="GET">
        <div class="searchBar" style="transform:translateX(42%);">
            <input type="text" name='query' id='query' style="width: 10%;">
            <input type="submit" value='Search' style="display: inline;">
        </div>
    </form>
    <a href="/" style="color: black; text-decoration:none;"><h1>To Do List</h1></a>
    <!-- form -->
    
    <form autocomplete="off" action="{% url 'create' %}" method='POST'>
        {% csrf_token %}
        <!-- <input type="text" name="textField" maxlength="450" required="" id="id_textField"> -->
            {{  form }}
        <input type="submit" value="ADD" >
    </form>
   
    <br>
    <br>
        <div class="tableContainer">
            <table>
                <tr>
                    <th>id</th>
                    <th>To Do List</th>
                    <th>Update/Delete</th>
                </tr>
                <tr class="table-data">

                </tr>
                {% for i in obj  %}
                        <tr class='table-data'>
                            <td>{{ i.id }}</td>
                            <td>{{ i.textField }}</td>
                            <td class='actionBtn'>
                                <a href="{% url 'update' i.id %}"><button  style="background-color: #2196F3;" >Update</button></a>
                                <a href="/delete/{{ i.id }}"><button style='background-color: #f44336; margin: 0 0 0 20px;'sonclick="openDel()">Delete</button></a>
                            </td>
                        </tr>
                {% endfor %}
                
            </table>

            {%  block del %}
            <div id="fixPosition" style="display: none;">
                <div class="container" style="width: 30rem; height: 15rem; background-color:black; position: absolute; left:50%; top:50%; transform:translate(-50%,-50%);"> 
                    <div class="text-Content" style=" color: white;">
                        <p style="padding:5px auto; background-color: cornsilk; color: black; font-size: 20px;"> <b>  Delete File </b> </p>
                        <p style="font-size: 18px; margin: 10px 0px 10px 10px;"> Are you sure you Want to delete?</p> 
                    </div>
                    <div class="modelForm" >
                        <form action="/delete/{{ i.id }}" method='POST'>
                        {% csrf_token %}
                            <input  type="submit" value='Yes' style='background-color: #f44336;' >
                        </form>
                            
                            <a href="/"><button style="background-color: #2196F3;
                                margin:1rem auto;
                                width: 5rem;
                                height: 2.5rem;
                                border: 2px solid black;
                                font-weight: bold;
                                color: white;
                                background-color: steelblue;
                                cursor: pointer;
                                transition: width 0.4s,height 0.4s;
                                ">Cancel</button></a>
                        
                    </div>
                </div>
            </div>

            <script src="{% static 'js.js' %}"></script>

            {% endblock %}
            
            <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
         
        
</body>
</html>

myapp/templates/search.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDoList</title>
    <style>

        *{
            margin: 0px;
            padding: 0px;
            /* box-sizing: border-box; */
            /* overflow: hidden; */
        }
        h1{
            font-family: 'Courier New', Courier, monospace;
            text-align: center;
            margin: 2rem 0 4rem 0;
        }

        form{
            margin: 1rem;
            text-align: center;
        }

        form label{
            font-family:Verdana, Geneva, Tahoma, sans-serif;
            display: block;
            margin-bottom: 0.5rem;
        }
        form input[type='text']{
            width: 50%;
            height:2.7rem;
            padding: 10px;
            font-size:1rem;
            transition: width 0.4s,height 0.4s
        }

        form input[type='text']:focus{
            width:51%;
            height:2.9rem;
        }

        form input[type='submit']{
            display: block;
            margin:1rem auto;
            width: 5rem;
            height: 2.5rem;
            border: 2px solid black;
            font-weight: bold;
            color: white;
            background-color: steelblue;
            cursor: pointer;
            transition: width 0.4s,height 0.4s;
        }
        form input[type='submit']:hover{
            width: 5.5rem;
            height:3rem;
        }

        .tableContainer{
            margin: 0 1rem 0 1rem;
        }
       .tableContainer table {
        font-family: helvetica,arial, sans-serif;
        width: 100%;
        }   

        td, th {
            border: 1.5px solid #131212;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
        td button{
            border: none;
            color: white;
            padding: 10px 24px;
            font-size: 14px;
            cursor: pointer;
            
        }


    </style>
</head>
<body>

    <form action="/search" method="GET">
        <div class="searchBar" style="transform:translateX(42%);">
            <input type="text" name='query' id='query' style="width: 10%;">
            <input type="submit" value='Search' style="display: inline;">
        </div>
    </form>
    <a href="/" style="color: black; text-decoration:none;"><h1>To Do List</h1></a>
    
    <h2 style="margin: 1rem;">Search Result:</h2>
    <br>
        <div class="tableContainer">
            <table>
                <tr>
                    <th>id</th>
                    <th>To Do List</th>
                    <th>Update/Delete</th>
                </tr>
                {% for i in allPost  %}
                    <tr>
                        <td>{{ i.id }}</td>
                        <td>{{ i.textField }}</td>
                        <td class='actionBtn'>
                            <a href="/update/{{ i.id }}"><button  style="background-color: #2196F3;" >Update</button></a>
                            <a href="/delete/{{ i.id }}"><button style='background-color: #f44336; margin: 0 0 0 20px;'>Delete</button></a>
                        </td>
                    </tr>
                    
                {% endfor %}
                
            </table>

         
        
</body>
</html>

myapp/templates/update.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update</title>
    <style>
        
        *{
            margin: 0px;
            padding: 0px;
            /* box-sizing: border-box; */
            /* overflow: hidden; */
        }
        h1{
            font-family: 'Courier New', Courier, monospace;
            text-align: center;
            margin: 2rem 0 4rem 0;
        }

        form{
            margin: 1rem;
            text-align: center;
        }

        form label{
            font-family:Verdana, Geneva, Tahoma, sans-serif;
            display: block;
            margin-bottom: 0.5rem;
        }
        form input[type='text']{
            width: 50%;
            height:2.7rem;
            padding: 10px;
            font-size:1rem;
            transition: width 0.4s,height 0.4s
        }

        form input[type='text']:focus{
            width:51%;
            height:2.9rem;
        }

        form input[type='submit']{
            display: block;
            margin:1rem auto;
            width: 5rem;
            height: 2.5rem;
            border: 2px solid black;
            font-weight: bold;
            color: white;
            background-color: steelblue;
            cursor: pointer;
            transition: width 0.4s,height 0.4s;
        }
        form input[type='submit']:hover{
            width: 5.5rem;
            height:3rem;
        }

    </style>
</head>
<body>
    <h1>To Do List</h1>
    <form action="/update/{{person.id }}" method='POST' autocomplete="off">
        {% csrf_token %}
        <input type="text" name='textField' id='textField' value='{{ person.textField }}'>
        <input type="submit" value="ADD">
    </form>
</body>
</html>